services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
      mongo-setup:
        condition: service_completed_successfully
    command: sh -c "npm install && npm run dev"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=csp-reporter
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-setup:
    image: mongo:7
    depends_on:
      - mongo
    volumes:
      - ./mongo-setup.sh:/mongo-setup.sh
    entrypoint: ["bash", "/mongo-setup.sh"]

volumes:
  mongo_data:
